title: Campbell Centre for the Study of Animal Welfare
description: Campbell Centre for the Study of Animal Welfare data documentation library
theme: just-the-docs

url: https://agrifooddatacanada.github.io/CCSAW/

aux_links:
  Template Repository: https://github.com/agrifooddatacanada/CCSAW
