title: Campbell Centre for the Study of Animal Welfare
description: Campbell Centre for the Study of Animal Welfare data documentation library
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/agrifooddatacanada/CCSAW
